name = "backend"
compatibility_date = "2024-07-13"

[vars]
JWT_SECRET = "SDFHS8849O3HDFBADHFPIHEF4839W"
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmVmYjllNmUtMGViOC00ZTVjLWE3MDktNGIzOTEyY2FlZjgyIiwidGVuYW50X2lkIjoiNTgyYzIxNTFlNGJjMjY5ZmIwNmMwNTEwZmU5MjBlZjgyMDVkYTIyNGVmMjRhMTZlMDNhNTExYWQzMThlMGY1NSIsImludGVybmFsX3NlY3JldCI6IjYxOGQwYmE1LTM1MDEtNDU1YS1iMjU5LTY1YTIzOGY5OTI3MCJ9.kAI6IxWpcyZ1iYvhKMRb2ZvJ2h0hx-z3kI9X0lDa-Mo"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"